from enum import StrEnum


class MigrationStatus(StrEnum):
    CREATED = "CREATED"
    UPLOADING = "UPLOADING"
    PROFILING = "PROFILING"
    MAPPING = "MAPPING"
    CLEANING = "CLEANING"
    RECONCILING = "RECONCILING"
    VALIDATING = "VALIDATING"
    WAITING_FOR_REVIEW = "WAITING_FOR_REVIEW"
    READY_TO_PUSH = "READY_TO_PUSH"
    PUSHING = "PUSHING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    CANCELLED = "CANCELLED"
    ROLLED_BACK = "ROLLED_BACK"
    PARTIALLY_COMPLETED = "PARTIALLY_COMPLETED"


class UserRole(StrEnum):
    IMPLEMENTATION_CONSULTANT = "IMPLEMENTATION_CONSULTANT"
    SENIOR_IMPLEMENTATION_CONSULTANT = "SENIOR_IMPLEMENTATION_CONSULTANT"
    HR_DATA_STEWARD = "HR_DATA_STEWARD"
    COMPENSATION_MANAGER = "COMPENSATION_MANAGER"
    PAYROLL_MANAGER = "PAYROLL_MANAGER"
    SYSTEM_ADMIN = "SYSTEM_ADMIN"


class EscalationStatus(StrEnum):
    OPEN = "OPEN"
    RESOLVED = "RESOLVED"
    REJECTED = "REJECTED"


class Severity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class DataClassification(StrEnum):
    INTERNAL = "INTERNAL"
    PERSONAL = "PERSONAL"
    PERSONAL_SENSITIVE = "PERSONAL_SENSITIVE"
    CONFIDENTIAL_COMPENSATION = "CONFIDENTIAL_COMPENSATION"
    RESTRICTED_PAYROLL = "RESTRICTED_PAYROLL"


class MappingDecision(StrEnum):
    PROPOSED = "PROPOSED"
    AUTO_APPROVED = "AUTO_APPROVED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    MANUALLY_APPROVED = "MANUALLY_APPROVED"
    MANUALLY_CORRECTED = "MANUALLY_CORRECTED"
    REJECTED = "REJECTED"
    BLOCKED = "BLOCKED"


class PushStatus(StrEnum):
    PENDING = "PENDING"
    PUSHING = "PUSHING"
    SUCCEEDED = "SUCCEEDED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_PERMANENT = "FAILED_PERMANENT"
    ROLLED_BACK = "ROLLED_BACK"


class AuditActorType(StrEnum):
    SYSTEM = "SYSTEM"
    USER = "USER"
    AGENT = "AGENT"
    TARGET = "TARGET"


class ValidationStatus(StrEnum):
    VALID = "VALID"
    INVALID = "INVALID"
    NEEDS_REVIEW = "NEEDS_REVIEW"
